# Generated by Django 4.2.7 on 2025-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detalles',
            field=models.TextField(blank=True, default='', verbose_name='Detalles de producto'),
        ),
    ]
