# Generated by Django 4.2.7 on 2025-04-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idioma',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='preferencias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telegram',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
